version: "3.9"

services:
  server:
    build:
      context: .
    env_file:
      - .env
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:16
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "$DB_USER"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - '${DB_PORT}'

volumes:
  postgres_data: